Repository BHoM/BHoM, pull requests merged in 2019-01, with the labels that each got.

#388 Outputs to imploement IObject instead of inheriting BHoMObject
  Reflection_oM/Output.cs
Labels: compliance, feature

#387 Add elementID property to BuildingElement
  Environment_oM/Elements/BuildingElement.cs
Labels: feature_minor

#394 Create PULL_REQUEST_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: compliance
