Repository BHoM/BHoM, pull requests merged in 2019-06, with the labels that each got.

#498 Issue497-BoundindBoxOperatorNullCheck
  Geometry_oM/Misc/BoundingBox.cs
Labels: severity:medium, size:S

#501 Environment_oM: Return space location point to Environment Space
  Environment_oM/Elements/Space.cs
Labels: severity:critical, size:XS

#511 Reflection_oM: Input & Output attributes
  Reflection_oM/Attributes/InputAttribute.cs
  Reflection_oM/Attributes/OutputAttribute.cs
Labels: size:XS
