Repository BHoM/BHoM, pull requests merged in 2019-10, with the labels that each got.

#562 Update code owners
  docs/CODEOWNERS
Labels: size:XS, type:compliance

#584 BHoM: Update assembly info
  Acoustic_oM/Properties/AssemblyInfo.cs
  Analytical_oM/Properties/AssemblyInfo.cs
  Architecture_oM/Properties/AssemblyInfo.cs
  BHoM/Properties/AssemblyInfo.cs
  BHoM_Test/Properties/AssemblyInfo.cs
  Common_oM/_Properties/AssemblyInfo.cs
  Data_oM/Properties/AssemblyInfo.cs
  Diffing_oM/Properties/AssemblyInfo.cs
  Environment_oM/_Properties/AssemblyInfo.cs
  Geometry_oM/Properties/AssemblyInfo.cs
  Graphics_oM/Properties/AssemblyInfo.cs
  Humans_oM/Properties/AssemblyInfo.cs
  Physical_oM/_Properties/AssemblyInfo.cs
  Planning_oM/Properties/AssemblyInfo.cs
  Reflection_oM/Properties/AssemblyInfo.cs
  Structure_oM/_Properties/AssemblyInfo.cs
  Testing_oM/Properties/AssemblyInfo.cs
Labels: type:compliance

#572 BHoM: Fragments to be `IObject` instead of `IBHoMObject`
  BHoM/Interface/IBHoMFragment.cs
Labels: severity:critical, size:XS, type:compliance

#592 Environment_oM: Update fragments
  Environment_oM/Fragments/BuildingAnalyticalFragment.cs
  Environment_oM/Fragments/BuildingContextFragment.cs
  Environment_oM/Fragments/BuildingResultFragment.cs
  Environment_oM/Fragments/CoefficientFragment.cs
  Environment_oM/Fragments/EnvironmentConstructionFragment.cs
  Environment_oM/Fragments/LightReflectanceFragment.cs
  Environment_oM/Fragments/LightTransmittanceFragment.cs
  Environment_oM/Fragments/LoadFragment.cs
  Environment_oM/Fragments/OriginContextFragment.cs
  Environment_oM/Fragments/PanelAnalyticalFragment.cs
  Environment_oM/Fragments/PanelContextFragment.cs
  Environment_oM/Fragments/RadiationFragment.cs
  Environment_oM/Fragments/SpaceAnalyticalFragment.cs
  Environment_oM/Fragments/SpaceContextFragment.cs
Labels: size:XS, status:WIP
