Repository BHoM/BHoM, pull requests merged in 2020-12, with the labels that each got.

#1075 Structure_oM: Updates to BarVaryingDistributedLoad
  Structure_oM/Loads/BarVaryingDistributedLoad.cs
Labels: status:do-not-merge, type:feature

#1099 Physical_oM: Add Construction Properties to Door and Window objects
  Physical_oM/Elements/IOpening.cs
  Physical_oM/Elements/Void.cs
Labels: type:feature

#1110 Environment_oM: Add Adiabatic Enum to PanelType
  Environment_oM/Elements/Enums/PanelType.cs
Labels: type:feature

#1121 Structure_oM: Remove Embodied Carbon from MaterialFragments
  Structure_oM/MaterialFragments/Aluminium.cs
  Structure_oM/MaterialFragments/Concrete.cs
  Structure_oM/MaterialFragments/GenericIsotropicMaterial.cs
  Structure_oM/MaterialFragments/GenericOrthotropicMaterial.cs
  Structure_oM/MaterialFragments/IMaterialFragment.cs
  Structure_oM/MaterialFragments/Steel.cs
  Structure_oM/MaterialFragments/Timber.cs
Labels: type:external-api-changes

#1122 Test_oM: Add TestResult and ResultStatus classes
  Test_oM/Results/Enums/ResultStatus.cs
  Test_oM/Results/TestResult.cs
  Test_oM/Test_oM.csproj
Labels: type:test-script
