Repository BHoM/BHoM, pull requests merged in 2020-03, with the labels that each got.

#725 DeepLearning_oM: Compliance Update
  DeepLearning_oM/DeepLearning_oM.csproj
  DeepLearning_oM/Layers/MaxUnPooling2d.cs
Labels: type:compliance

#724 Data_oM: Compliance Update
  Data_oM/Library/Dataset.cs
Labels: type:compliance

#726 Geometry_oM: Compliance Update
  Geometry_oM/Geometry_oM.csproj
  Geometry_oM/Surface/PolySurface.cs
Labels: type:compliance

#736 Base_oM: Base BHoMObject Properties now all Virtual
  BHoM/BHoMObject.cs
Labels: type:feature

#742 Architecture_oM: Update room to be IElement2D
  Architecture_oM/Elements/Room.cs
Labels: type:feature

#659 BHoM: Added null check to `FragmentSet` constructor with `fragmentSet` argument.
  BHoM/FragmentSet.cs
Labels: type:bug

#730 Physical_oM: Add IElementXD to physical objects
  Physical_oM/Elements/IFramingElement.cs
  Physical_oM/Elements/IOpening.cs
  Physical_oM/Elements/ISurface.cs
Labels: type:feature

#747 BHoM: Fix CI files
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
Labels: type:compliance
