Repository BHoM/BHoM, pull requests merged in 2020-10, with the labels that each got.

#1004 LifeCycleAssessment_oM: Update EPD Object Properties
  LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
  LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
  LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs
Labels: type:feature

#992 Geometry_oM: Added InterpolationOrder and added shape to constructor for TaperedProfile
  Geometry_oM/ShapeProfiles/TaperedProfile.cs
Labels: severity:medium, size:S, type:feature

#1026 Geometry_oM: Addition of Volume as a Get only Property to BoundaryRepresentation
  Geometry_oM/Solid/BoundaryRepresentation.cs
Labels: type:feature

#1028 Programming_oM: Remove dependency to GetShallowClone
  Programming_oM/Nodes/BlockNode.cs
  Programming_oM/Nodes/LoopNode.cs
Labels: type:compliance

#1039 MEP_oM: Creation of VolumeDamper Object
  MEP_oM/Elements/VolumeDamper.cs
  MEP_oM/MEP_oM.csproj
Labels: type:feature

#1047 Graphics_oM: Make RenderMesh a Fragment
  Graphics_oM/Render/RenderMesh.cs
  Graphics_oM/Render/RenderMeshOptions.cs
Labels: severity:critical, type:compliance, type:feature

#1056 Humans_oM: Adding "Manager" property to Employee; added descriptions
  Humans_oM/Employee.cs
Labels: type:feature
