Repository BHoM/BHoM, pull requests merged in 2020-11, with the labels that each got.

#1060 Facade_oM: Creation of Initial Facade_oM
  BHoM.sln
  Facade_oM/Elements/CurtainWall.cs
  Facade_oM/Elements/Enums/FrameCornerType.cs
  Facade_oM/Elements/Enums/FrameEdgeType.cs
  Facade_oM/Elements/Enums/OpeningType.cs
  Facade_oM/Elements/Enums/PanelType.cs
  Facade_oM/Elements/FrameEdge.cs
  Facade_oM/Elements/Opening.cs
  Facade_oM/Elements/Panel.cs
  Facade_oM/Facade_oM.csproj
  Facade_oM/IFacadeObject.cs
  Facade_oM/IProperty.cs
  Facade_oM/Properties/AssemblyInfo.cs
  Facade_oM/SectionProperties/FrameEdgeProperty.cs
Labels: type:feature

#1062 Reflection_oM: Improved name change support on method arguments
  Reflection_oM/Attributes/PreviousInputNames.cs
  Reflection_oM/Reflection_oM.csproj
Labels: type:bug

#1066 LifeCycleAssessment_oM: Update ObjectCategory.cs
  LifeCycleAssessment_oM/Enums/ObjectCategory.cs
Labels: type:feature

#1049 Graphics_oM: add ColourFragment
  Graphics_oM/Colours/ColourFragment.cs
  Graphics_oM/Colours/Gradient.cs
  Graphics_oM/Graphics_oM.csproj
Labels: type:feature

#1071 Structure_oM: Fixing default values of some properties
  Structure_oM/Elements/FEMesh.cs
  Structure_oM/Elements/Panel.cs
  Structure_oM/SectionProperties/ConcreteSection.cs
Labels: type:compliance

#1082 Reflection_oM: Path attribute classes made non-abstract
  Reflection_oM/Attributes/FilePathAttribute.cs
  Reflection_oM/Attributes/FolderPathAttribute.cs
Labels: type:bug

#1092 Reflection_oM: Add UTC time to events
  Reflection_oM/Debugging/Event.cs
Labels: type:bug
