Repository BHoM/BHoM, pull requests merged in 2020-06, with the labels that each got.

#902 Add Air as PanelType
  Environment_oM/Elements/Enums/PanelType.cs
Labels: type:feature

#905 Environment_oM: Add ACH to Exhaust Object
  Environment_oM/Gains/Exhaust.cs
Labels: type:feature

#909 Spatial_oM: Correct reference to Reflection_oM
  Spatial_oM/Spatial_oM.csproj
Labels: type:compliance

#907 Architecture_oM: Remove Common_oM dependant Objects
  Architecture_oM/Architecture_oM.csproj
  Architecture_oM/Elements/Floor.cs
  Architecture_oM/Elements/Roof.cs
  Architecture_oM/Elements/Wall.cs
Labels: type:compliance

#906 Common_oM: Move IPhase & ConstructionPhase to Planning_oM
  Common_oM/Common_oM.csproj
  Planning_oM/Construction/ConstructionPhase.cs
  Planning_oM/IPhase.cs
  Planning_oM/Planning_oM.csproj
Labels: type:compliance

#926 LifeCycleAssessment_oM: Fix invalid constructor
  LifeCycleAssessment_oM/Results/LifeCycleAssessmentResult.cs
Labels: type:compliance

#930 LifeCycleAssessment_oM: Update ProjectArea Enum
  LifeCycleAssessment_oM/Enums/ProjectArea.cs
Labels: good first issue, size:XS, type:bug

#923 Data_oM: logical IRequest descriptions cleaned up
  Data_oM/Requests/LogicalAndRequest.cs
  Data_oM/Requests/LogicalNotRequest.cs
  Data_oM/Requests/LogicalOrRequest.cs
Labels: type:documentation
