Repository BHoM/BHoM, pull requests merged in 2020-02, with the labels that each got.

#679 Environment_oM : Add IBHoMFragment to EnvironmentMaterial Fragments
  Environment_oM/MaterialFragments/GasMaterial.cs
  Environment_oM/MaterialFragments/IEnvironmentMaterial.cs
  Environment_oM/MaterialFragments/SolidMaterial.cs
Labels: type:compliance

#685 Update CI files
  .ci/CloneTest.ps1
Labels: type:bug, type:compliance

#687 Environment_oM: AnalyticalConstruction fragment
  Analytical_oM/Analytical_oM.csproj
  Analytical_oM/Elements/IAnalyticalConstruction.cs
  Environment_oM/Fragments/AnalyticalConstruction.cs
Labels: type:feature

#699 Creation of new Dimensional_oM
  BHoM.sln
  Dimensional_oM/Dimensional_oM.csproj
  Dimensional_oM/Properties/AssemblyInfo.cs
Labels: type:compliance

#695 Reflection_oM: Add InputFromProperty attribute
  Reflection_oM/Attributes/InputFromProperty.cs
  Reflection_oM/Reflection_oM.csproj
Labels: type:feature

#706 Quantities_oM: Adding mass per unit area and mass per unit length
  Quantities_oM/Attributes/MassPerUnitArea.cs
  Quantities_oM/Attributes/MassPerUnitLength.cs
  Quantities_oM/Quantities_oM.csproj
Labels: type:feature

#709 Data_oM: SelectionRequest added
  Data_oM/Data_oM.csproj
  Data_oM/Requests/SelectionRequest.cs
Labels: size:XS, type:feature

#711 BHoM: Rename IBHoMFragment -> IFragment
  BHoM/BHoM.csproj
  BHoM/FragmentSet.cs
  BHoM/Interface/IFragment.cs
  Diffing_oM/HashFragment.cs
  Environment_oM/Fragments/AnalyticalConstruction.cs
  Environment_oM/Fragments/BuildingAnalyticalFragment.cs
  Environment_oM/Fragments/BuildingContextFragment.cs
  Environment_oM/Fragments/BuildingResultFragment.cs
  Environment_oM/Fragments/CoefficientFragment.cs
  Environment_oM/Fragments/EnvironmentConstructionFragment.cs
  Environment_oM/Fragments/LightReflectanceFragment.cs
  Environment_oM/Fragments/LightTransmittanceFragment.cs
  Environment_oM/Fragments/LoadFragment.cs
  Environment_oM/Fragments/OriginContextFragment.cs
  Environment_oM/Fragments/PanelAnalyticalFragment.cs
  Environment_oM/Fragments/PanelContextFragment.cs
  Environment_oM/Fragments/RadiationFragment.cs
  Environment_oM/Fragments/SpaceAnalyticalFragment.cs
  Environment_oM/Fragments/SpaceContextFragment.cs
  Environment_oM/MaterialFragments/GasMaterial.cs
  Environment_oM/MaterialFragments/IEnvironmentMaterial.cs
  Environment_oM/MaterialFragments/SolidMaterial.cs
  MEP_oM/Fragments/Geometry.cs
  MEP_oM/Fragments/Identity.cs
  Structure_oM/MaterialFragments/IMaterialFragment.cs
Labels: type:compliance
