Repository BHoM/BHoM, pull requests merged in 2020-01, with the labels that each got.

#642 BHoM: Update assembly file version to 3.1.0.0
  Acoustic_oM/Properties/AssemblyInfo.cs
  Analytical_oM/Properties/AssemblyInfo.cs
  Architecture_oM/Properties/AssemblyInfo.cs
  BHoM/Properties/AssemblyInfo.cs
  Common_oM/_Properties/AssemblyInfo.cs
  Data_oM/Properties/AssemblyInfo.cs
  DeepLearning_oM/Properties/AssemblyInfo.cs
  Diffing_oM/Properties/AssemblyInfo.cs
  Environment_oM/_Properties/AssemblyInfo.cs
  Geometry_oM/Properties/AssemblyInfo.cs
  Graphics_oM/Properties/AssemblyInfo.cs
  Humans_oM/Properties/AssemblyInfo.cs
  MEP_oM/Properties/AssemblyInfo.cs
  Physical_oM/_Properties/AssemblyInfo.cs
  Planning_oM/Properties/AssemblyInfo.cs
  Reflection_oM/Properties/AssemblyInfo.cs
  Structure_oM/_Properties/AssemblyInfo.cs
Labels: type:compliance

#629 Geometry_oM: TaperedProfile added
  Geometry_oM/Geometry_oM.csproj
  Geometry_oM/ShapeProfiles/TaperedProfile.cs
Labels: severity:medium, size:S, type:feature

#666 Update Copyright Header
  COPYRIGHT_HEADER.txt
Labels: type:compliance

#669 Structure_oM: Update description of orientation angle for Bar
  Structure_oM/Elements/Bar.cs
Labels: type:documentation
