Repository BHoM/BHoM, pull requests merged in 2020-09, with the labels that each got.

#974 Structure_oM: Adding OrientationAngle to Panel
  Structure_oM/Elements/FEMeshFace.cs
  Structure_oM/Elements/Panel.cs
Labels: type:feature

#996 Acoustic_oM: Set Acoustic.Panel PanelID Property as virtual
  Acoustic_oM/Elements/Panel.cs
Labels: type:compliance

#999 Structure_oM: Fix ModalDynamics constructor
  Structure_oM/Results/Global Results/ModalDynamics.cs
Labels: type:bug
