Repository BHoM/BHoM, pull requests merged in 2020-05, with the labels that each got.

#846 Diffing_oM: remove CustomData from the default "Ignores" of DiffConfig
  Diffing_oM/DiffConfig.cs
Labels: size:XS, type:feature

#826 Update README.md and docs
  CONTRIBUTING.md
  README.md
  docs/GOVERNANCE.md
Labels: type:documentation

#849 Reflection_oM: Fix PreviousVersionAttribute constructor
  Reflection_oM/Attributes/PreviousVersionAttribute.cs
Labels: type:compliance

#853 BHoM: Add a constructor from List for FragmentSet
  BHoM/FragmentSet.cs
Labels: type:feature

#859 LifeCycleAssessment_oM: iEnvironmentalProductDeclaration MaterialFragments
  LifeCycleAssessment_oM/LifeCycleAssessment_oM.csproj
  LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
  LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
  LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs
Labels: type:feature

#857 Diffing_oM: Fix non-compliant constructor for StreamPointer
  Diffing_oM/StreamPointer.cs
Labels: type:compliance

#876 Environment_oM: Add space perimeter curve to Space object
  Environment_oM/Elements/Space.cs
Labels: type:feature

#878 Add Hole as OpeningType
  Environment_oM/Elements/Enums/OpeningType.cs
Labels: type:feature

#884 Environment_oM: Modify Space Object and Ventilation
  Environment_oM/Elements/Space.cs
  Environment_oM/Environment_oM.csproj
  Environment_oM/Ventilation/Ventilation.cs
Labels: type:feature

#897 Environment_oM: Fix AnalysisGrid for IImutability
  Environment_oM/Analysis/AnalysisGrid.cs
Labels: type:compliance
