Repository BHoM/BHoM, pull requests merged in 2020-04, with the labels that each got.

#781 Environment_oM: Updated Ventilation Object with AirChangeRate property
  Environment_oM/Gains/Ventilation.cs
Labels: severity:low, type:feature

#788 Data_Engine: Add generic graph query methods
  Data_oM/Data_oM.csproj
  Data_oM/Enums/GraphLinkDirection.cs
Labels: type:feature

#799 Environments_oM: Updated Infiltration Gain Object Properties
  Environment_oM/Gains/Infiltration.cs
Labels: type:feature

#801 Environment_oM: Add Acoustics Object
  Environment_oM/Environment_oM.csproj
  Environment_oM/Gains/Acoustics.cs
Labels: type:feature

#814 Structure_oM: Implement IElementM for Area elements
  Structure_oM/Elements/IAreaElement.cs
Labels: type:feature

#796 Architecture_oM: Created Occupancy Under Arch oM
  Architecture_oM/Architecture_oM.csproj
  Architecture_oM/Elements/Occupancy.cs
Labels: type:feature

#833 Diffing_oM: added constructor to DeltaPayload class to fix serialisation error
  Diffing_oM/AECDeltas/DeltaPayload.cs
Labels: size:XS, type:bug

#835 Reflection_oM: Fix invalid IImmutable constructor parameter names
  Reflection_oM/Attributes/DeprecatedAttribute.cs
  Reflection_oM/Attributes/ReplacedAttribute.cs
Labels: type:bug
