Repository BHoM/BHoM, pull requests merged in 2022-01, with the labels that each got.

#1347 Spatial_oM: Migrating grids and levels to Spatial
  Architecture_oM/Elements/Grid.cs
  Geometry_oM/SettingOut/Grid.cs
  Spatial_oM/SettingOut/Grid.cs
  Spatial_oM/SettingOut/Level.cs
  Spatial_oM/Versioning_51.json
Labels: type:compliance

#1341 Physical_oM: Removes all checks from the constructor of the MaterialComposition
  Physical_oM/Materials/MaterialComposition.cs
Labels: type:compliance

#1314 Added Layer and Layered surface property
  Structure_oM/SurfaceProperties/Layer.cs
  Structure_oM/SurfaceProperties/Layered.cs
Labels: type:feature

#1349 Environment_oM: TranslucentShade panel type
  Environment_oM/Elements/Enums/PanelType.cs
Labels: size:S, type:feature
