Repository BHoM/BHoM, pull requests merged in 2023-11, with the labels that each got.

#1563 BHoM: Update documentation links and references
  README.md
  docs/CODE_OF_CONDUCT_FOR_BOTS.md
  docs/GOVERNANCE.md
Labels: type:compliance

#1566 Dimensional_oM: Updating DocumentationURL ref IElement Required Methods
  Dimensional_oM/IElement0D.cs
  Dimensional_oM/IElement1D.cs
  Dimensional_oM/IElement2D.cs
  Dimensional_oM/IElementM.cs
Labels: type:documentation

#1565 Structure_oM: Added IAreaElements to GeometricalLineloads
  Structure_oM/Loads/GeometricalLineLoad.cs
Labels: type:feature

#1568 Update README.md
  README.md
Labels: type:documentation
