Repository BHoM/BHoM, pull requests merged in 2024-01, with the labels that each got.

#1576 BHoM: Documentation Link updates
  CONTRIBUTING.md
  Structure_oM/Elements/Bar.cs
  Structure_oM/Elements/Pile.cs
Labels: type:documentation

#1578 BHoM: Update COPYRIGHT_HEADER.txt to 2024
  COPYRIGHT_HEADER.txt
Labels: type:compliance

#1577 BHoM: Legacy attributes removed
  BHoM/Attributes/AssemblyUrlAttribute.cs
  BHoM/Attributes/ReleasedAttribute.cs
  BHoM/Versioning_71.json
Labels: type:compliance

#1579 Analytical_oM: Rename StartNode/EndNode to Start/Node
  Analytical_oM/Elements/ILink.cs
  Analytical_oM/Versioning_71.json
  Structure_oM/Elements/Bar.cs
  Structure_oM/Versioning_71.json
Labels: type:compliance

#1580 Analytical_oM: Elevate Graph objects from Elements sub folder to own primary folder
  Analytical_oM/Graph/Graph.cs
  Analytical_oM/Graph/IRelation.cs
  Analytical_oM/Graph/Projection/GeometricProjection.cs
  Analytical_oM/Graph/Projection/GraphicalProjection.cs
  Analytical_oM/Graph/Projection/IProjection.cs
  Analytical_oM/Graph/Projection/SpatialProjection.cs
  Analytical_oM/Graph/Relation.cs
  Analytical_oM/Graph/RelationDirection.cs
  Analytical_oM/Results/ShortestPathResult.cs
  Analytical_oM/Versioning_71.json
Labels: type:compliance

#1581 Structure_oM: Remove deprecated reinforcement objects
  Structure_oM/SectionProperties/Reinforcement/Deprecated/LayerReinforcement.cs
  Structure_oM/SectionProperties/Reinforcement/Deprecated/PerimeterReinforcement.cs
  Structure_oM/SectionProperties/Reinforcement/Deprecated/Reinforcement.cs
  Structure_oM/SectionProperties/Reinforcement/Deprecated/TieReinforcement.cs
  Structure_oM/Versioning_71.json
Labels: type:compliance

#1582 Structure_oM: Rename PointForce to PointLoad
  Structure_oM/Loads/Enums/LoadType.cs
Labels: type:compliance

#1583 Diffing_oM: Rename Id to ID as appropriate
  Diffing_oM/AECDeltas/DeltaPayload.cs
  Diffing_oM/Delta.cs
  Diffing_oM/DiffingConfig.cs
  Diffing_oM/Revision.cs
  Diffing_oM/StreamPointer.cs
  Diffing_oM/Versioning_71.json
Labels: type:compliance

#1586 Search_oM: Migrate Search_oM to the core oM
  .github/CODEOWNERS
  BHoM.sln
  Search_oM/Enums/Scorer.cs
  Search_oM/SearchResult.cs
  Search_oM/Search_oM.csproj
Labels: type:feature
